[package]
name = "taured_tui"
description = "taured is a distro-agnostic Linux toolbox for everyday system tasks."
readme = "../README.md"
edition = "2021"
license.workspace = true
repository = "https://github.com/nibir-d7/taured/tree/main/tui"
version.workspace = true
include = [
    "src/*.rs",
    "Cargo.toml",
    "cool_tips.txt",
]

[[bin]]
name = "taured"
path = "src/main.rs"

[features]
default = ["tips"]
tips = ["rand"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
taured_core = { version = "0.1.0", path = "../core" }
nix = { version = "0.31.3", features = ["user"] }
oneshot = { version = "0.2.1", features = ["std"], default-features = false }
portable-pty = "0.9.0"
rand = { version = "0.10.1", optional = true }
ratatui = { version = "0.30.0", features = ["crossterm"], default-features = false }
time = { version = "0.3.47", features = ["formatting", "local-offset", "macros"], default-features = false }
tree-sitter-bash = "0.25.1"
tree-sitter-highlight = "0.26.9"
tui-term = { version = "0.3.4", default-features = false }
unicode-width = { version = "0.2.0", default-features = false }
vt100-ctt = "0.17.1"
