[package]
name = "taured_tui"
description = "taured - distro-agnostic Linux toolbox"
readme = "../README.md"
edition = "2021"
license.workspace = true
repository = "https://github.com/nibir-d7/taured/tree/main/tui"
version.workspace = true

[[bin]]
name = "taured"
path = "src/main.rs"

[dependencies]
taured_core = { version = "0.1.0", path = "../core" }
ratatui = { version = "0.30.0", features = ["crossterm"], default-features = false }
crossterm = "0.28"
unicode-width = { version = "0.2.0", default-features = false }