import type { App } from "@/lib/types";

export function buildLinuxScript(apps: App[]): string {
  const lines: string[] = [];
  lines.push("#!/usr/bin/env bash");
  lines.push("# taured.space — Linux setup script");
  lines.push("# Generated by taured.space. Review every line before running.");
  lines.push("# Back up important data first. Run: bash taured-setup-linux.sh");
  lines.push("set -euo pipefail");
  lines.push("");
  lines.push('if [ "$(id -u)" -ne 0 ]; then echo "Run with sudo"; exit 1; fi');
  lines.push("");
  lines.push("if command -v apt-get >/dev/null; then PM=apt; elif command -v dnf >/dev/null; then PM=dnf; elif command -v pacman >/dev/null; then PM=pacman; else echo 'No supported package manager'; exit 1; fi");
  lines.push('echo "Detected package manager: $PM"');
  lines.push("");
  for (const app of apps) {
    const pkgs: Record<string, string | null> = {
      apt: app.linux_apt,
      dnf: app.linux_dnf,
      pacman: app.linux_pacman,
    };
    const pkg = pkgs["apt"] ?? Object.values(pkgs).find(Boolean);
    lines.push(`# ${app.name}`);
    if (app.linux_flatpak) {
      lines.push(`# flatpak option: flatpak install -y ${app.linux_flatpak}`);
    }
    if (app.linux_snap) {
      lines.push(`# snap option: snap install ${app.linux_snap}`);
    }
    if (pkg) {
      lines.push(`case "$PM" in`);
      if (app.linux_apt) lines.push(`  apt) DEBIAN_FRONTEND=noninteractive apt-get install -y ${app.linux_apt} ;;`);
      if (app.linux_dnf) lines.push(`  dnf) dnf install -y ${app.linux_dnf} ;;`);
      if (app.linux_pacman) lines.push(`  pacman) pacman -S --noconfirm ${app.linux_pacman} ;;`);
      lines.push(`  *) echo "no mapping for ${app.name}" ;;`);
      lines.push(`esac`);
    } else {
      lines.push(`# no native package mapping for ${app.name}`);
    }
    lines.push("");
  }
  lines.push('echo "Done."');
  return lines.join("\n");
}
