import type { App } from "@/lib/types";

export function buildWindowsScript(apps: App[]): string {
  const lines: string[] = [];
  lines.push("# taured.space — Windows setup script");
  lines.push("# Generated by taured.space. Review every line before running.");
  lines.push("# Create a system restore point first:");
  lines.push("#   Checkpoint-Computer -Description 'Before taured setup' -RestorePointType MODIFY_SETTINGS");
  lines.push("# Run in an elevated PowerShell: Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass");
  lines.push("");
  lines.push("$ErrorActionPreference = 'Stop'");
  lines.push("");
  for (const app of apps) {
    if (app.win_winget) {
      lines.push(`# ${app.name}`);
      lines.push(`winget install --id ${app.win_winget} -e --source winget || choco install ${app.win_choco ?? app.win_winget} -y`);
      lines.push("");
    } else if (app.win_choco) {
      lines.push(`# ${app.name}`);
      lines.push(`choco install ${app.win_choco} -y`);
      lines.push("");
    } else {
      lines.push(`# ${app.name}: no Windows installer mapping — add one in /admin`);
      lines.push("");
    }
  }
  lines.push('Write-Host "Done. Reboot recommended."');
  return lines.join("\n");
}
