name = "Security"

[[data]]
name = "FirewallD Firewall Baselines"
description = "Configure FirewallD with recommended baseline rules for improved system security."
script = "firewalld-baselines.sh"
task_list = "I SS"

[[data.preconditions]]
matches = true
data = "command_exists"
values = [ "firewall-cmd" ]
[[data]]
name = "Lynis Security Audit"
description = "Install Lynis when needed, run an elevated system security audit with live results, then optionally remove Lynis."
script = "lynis-audit.sh"
task_list = "I MP RP"
multi_select = false

[[data]]
name = "UFW Firewall Baselines"
description = "Developed to ease iptables firewall configuration, UFW provides a user friendly way to create an IPv4 or IPv6 host-based firewall. This command installs UFW and configures it with recommended rules."
script = "ufw-baselines.sh"
task_list = "I SS"

[[data.preconditions]]
matches = false
data = "command_exists"
values = [ "firewall-cmd" ]
